### ISSUE TITLE
Please document how to transpile this code

### ISSUE THREAD

**Issue by mblythe86** [bpatrik/pigallery2-sample-extension#1]
Please bear with me... I'm a novice at node/npm/typescript, so it's likely that I'm missing something that would be obvious to someone more familiar with these tools.

I'm using this sample as a starting point for my own extension, but when I try to transpile it, I get a slew of errors.

For example, just running `tsc server.ts` gave me `error TS2468: Cannot find global value 'Promise'.`  I finally figured out that I needed to add `--lib es2015`.

Likewise, `error TS2584: Cannot find name 'console'.` seems to suggest that I need `--lib es2015,dom`.

Even with those changes, I'm getting errors like `error TS2307: Cannot find module './lib/src/backend/model/extension/IExtension' or its corresponding type declarations.`.  I feel like this means that I need to clone this repo within a pigallery2 repo?

**Comment by bpatrik** [comment]
Made some changes, but it seems to be a way more complex on its own, when I try to build the extension separately from the main project. 

Basically through the dev-kit the extension has a dependency to whole pigallery2 project and to all of its dependencies. I will need to cut that that dependency somewhere to make the extension more contained.

Until that is fixed  I added a bunch of dev dependency to this sample extension.

now you should be able to 
`npm intall`
`npm run build`

**Comment by mblythe86** [comment]
Thank you!

I can confirm that the following works as expected (at least on Ubuntu 22.04):

```
git clone https://github.com/bpatrik/pigallery2-sample-extension.git my_extension
cd my_extension
npm install
npm run build
```

> Basically through the dev-kit the extension has a dependency to whole pigallery2 project and to all of its dependencies. I will need to cut that that dependency somewhere to make the extension more contained.

IMO, this dependency seems justified for extension development.  Some of these hooks look like they can reach pretty deep into the inner workings of pigallery2, so I'm not sure how much they can be decoupled anyway.
